CREATE TABLE IF NOT EXISTS USERS(
    ID UUID PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
);

CREATE TYPE TRANSACTION_TYPE AS ENUM ('EARNING', 'EXPENSE', 'INVESTIMENT');

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
    ID UUID PRIMARY KEY,
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DATE DATE NOT NULL,
    AMOUNT NUMERIC(10, 2) NOT NULL,
    TYPE TRANSACTION_TYPE NOT NULL
);

